export const KNOWN_ACTIONS = [
    { testid: 'nav-logo', description: 'Navigate to dashboard' },
    { testid: 'nav-home', description: 'Navigate home' },
    { testid: 'nav-back', description: 'Navigate back' },
    { testid: 'nav-settings', description: 'Open settings' },
    { testid: 'nav-profile', description: 'Open profile menu' },
    { testid: 'nav-signup', description: 'Open signup' },
    { testid: 'nav-insights', description: 'Open insights' },
    { testid: 'nav-global-analytics', description: 'Open analytics' },
    { testid: 'profile-sync', description: 'Manual sync' },
    { testid: 'profile-check-updates', description: 'Check updates' },
    { testid: 'profile-logout', description: 'Logout', destructive: true },
    { testid: 'deck-create-manual', description: 'Create deck manually' },
    { testid: 'deck-import', description: 'Import deck' },
    { testid: 'deck-create-ai', description: 'Create deck with AI' },
    { testid: 'deck-open-*', description: 'Open deck detail' },
    { testid: 'deck-edit', description: 'Edit deck' },
    { testid: 'deck-settings', description: 'Open deck settings' },
    { testid: 'deck-export', description: 'Export deck' },
    { testid: 'deck-delete', description: 'Delete deck', destructive: true },
    { testid: 'deck-reset', description: 'Reset deck progress', destructive: true },
    { testid: 'deck-save', description: 'Save deck' },
    { testid: 'deck-add-card', description: 'Add card' },
    { testid: 'deck-notes-upload', description: 'Upload notes image' },
    { testid: 'mode-learn-start', description: 'Start learn mode' },
    { testid: 'mode-review-start', description: 'Start review mode' },
    { testid: 'mode-spaced-start', description: 'Start spaced mode' },
    { testid: 'mode-sequence-start', description: 'Start sequence mode' },
    { testid: 'mode-practice-start', description: 'Start practice test' },
    { testid: 'study-continue-round', description: 'Continue study round' },
    { testid: 'study-reset-progress', description: 'Reset study progress', destructive: true },
    { testid: 'study-instructions', description: 'Study instructions' },
    { testid: 'study-edit-card', description: 'Edit study card' },
    { testid: 'study-switch-mode', description: 'Switch study mode' },
    { testid: 'answer-show', description: 'Show answer' },
    { testid: 'answer-show-question', description: 'Show question' },
    { testid: 'answer-check', description: 'Check answer' },
    { testid: 'answer-dont-know', description: 'Dont know answer' },
    { testid: 'answer-next', description: 'Next card' },
    { testid: 'answer-incorrect', description: 'Mark incorrect' },
    { testid: 'answer-correct', description: 'Mark correct' },
    { testid: 'rating-again', description: 'Spaced rating again' },
    { testid: 'rating-hard', description: 'Spaced rating hard' },
    { testid: 'rating-good', description: 'Spaced rating good' },
    { testid: 'rating-easy', description: 'Spaced rating easy' },
    { testid: 'sequence-submit', description: 'Sequence submit' },
    { testid: 'sequence-continue', description: 'Sequence continue' },
    { testid: 'study-end-session', description: 'End session' },
    { testid: 'study-end-session-complete', description: 'End session complete' },
    { testid: 'study-restart', description: 'Restart study' },
    { testid: 'pomodoro-toggle', description: 'Toggle pomodoro' },
    { testid: 'pomodoro-reset', description: 'Reset pomodoro' },
    { testid: 'test-start', description: 'Start practice test' },
    { testid: 'test-instructions', description: 'Practice test instructions' },
    { testid: 'test-show-answer', description: 'Show practice answer' },
    { testid: 'test-check-answer', description: 'Check practice answer' },
    { testid: 'test-incorrect', description: 'Practice mark incorrect' },
    { testid: 'test-correct', description: 'Practice mark correct' },
    { testid: 'test-next', description: 'Practice next' },
    { testid: 'test-review', description: 'Practice review' },
    { testid: 'test-apply-learning', description: 'Apply learning' },
    { testid: 'test-restart', description: 'Restart test' },
    { testid: 'test-end', description: 'End test' },
    { testid: 'import-tab-paste', description: 'Import paste tab' },
    { testid: 'import-tab-file', description: 'Import file tab' },
    { testid: 'import-confirm', description: 'Import confirm' },
    { testid: 'import-create', description: 'Import create' },
    { testid: 'learn-setup-start', description: 'Start learn setup' },
    { testid: 'learn-setup-cancel', description: 'Cancel learn setup' },
    { testid: 'deck-settings-save', description: 'Save deck settings' },
    { testid: 'deck-settings-cancel', description: 'Cancel deck settings' },
    { testid: 'edit-card-save', description: 'Save edited card' },
    { testid: 'edit-card-cancel', description: 'Cancel card edit' },
    { testid: 'settings-save-name', description: 'Save username' },
    { testid: 'settings-save-study', description: 'Save study settings' },
    { testid: 'settings-export-data', description: 'Export data' },
    { testid: 'settings-clear-decks', description: 'Clear all decks', destructive: true },
    { testid: 'settings-dark-mode', description: 'Toggle dark mode' },
    { testid: 'settings-editing', description: 'Toggle in-study editing' },
    { testid: 'settings-toasts', description: 'Toggle toasts' },
    { testid: 'settings-exam-banner', description: 'Toggle exam banner' },
    { testid: 'settings-pomodoro', description: 'Toggle pomodoro' },
    { testid: 'settings-adaptive-auto', description: 'Toggle adaptive auto' },
    { testid: 'settings-adaptive-mcq', description: 'Toggle adaptive mcq' },
    { testid: 'settings-adaptive-cloze', description: 'Toggle adaptive cloze' },
    { testid: 'settings-case-sensitive', description: 'Toggle case sensitivity' },
    { testid: 'settings-punctuation', description: 'Toggle punctuation' },
    { testid: 'confirm-cancel', description: 'Cancel confirm' },
    { testid: 'confirm-confirm', description: 'Confirm action', destructive: true }
];

export function resolveActionConfig(testid) {
    if (!testid) return null;
    const direct = KNOWN_ACTIONS.find(action => action.testid === testid);
    if (direct) return direct;
    const prefixMatch = KNOWN_ACTIONS.find(action => action.testid.endsWith('*') && testid.startsWith(action.testid.slice(0, -1)));
    return prefixMatch || null;
}
